### ISSUE TITLE
Link to source results in 404

### ISSUE THREAD

**Issue by mewmew** [Predelnik/Scripture#4]
I tried updating to the latest version (see commit sanctuary/notes@32d884d8b2bbbaeec00f8c663807a351331450b9), and some things have improved. E.g. the Source file path is now displayed with `/` rather than `\`. However, the links to the source code stopped working.

For instance, see http://sanctuary.github.io/notes/#function/trigs_init_warps_town where the Source link results in 404 at https://github.com/sanctuary/notes/blob/mastermaster/funcs/trigs.cpp#L16

**Comment by mewmew** [comment]
For reference, this is what I ran to generate the page:

```bash
#!/bin/bash
notes_dir="/home/u/Desktop/go/src/github.com/sanctuary/notes"
python extract.py --args="-I$notes_dir" "$notes_dir" --github-root="https://github.com/sanctuary/notes/blob/master"
```

**Comment by Predelnik** [comment]
Yeah now `--github-root` should be specified without master, I should have updated readme.md. Since as you can see master is duplicated in the link.

I also added `--github-sha1` to make links to the exact revision, just so they would be stable if master updated. So it's technically better to run with --github1-sha1= _result of "git rev-parse HEAD" made in appropriate directory_ 

But it should work fine without it, defaulting to master just using 

         --github-root="https://github.com/sanctuary/notes/blob/"

Slashes are solely dependent on user's system and I guess it should be fixed.

By the way testing locally is super easy nowadays (even on windows) I just use `python -mhttp.server` for it.

**Comment by mewmew** [comment]
> By the way testing locally is super easy nowadays (even on windows) I just use `python -mhttp.server` for it.

Yes, felt happy to discover that it works so easy locally. I ran the `http` tool Rust cargo named https: https://gist.github.com/mewmew/2dc7cd521bee147ca825d7addc1703cb#gistcomment-2352406 and that worked great.

> Slashes are solely dependent on user's system and I guess it should be fixed.

A bit of a preference I guess, but yes. Preferably the site should look identical no matter what platform it is generated on

> But it should work fine without it, defaulting to master just using

```bash
     --github-root="https://github.com/sanctuary/notes/blob/"
```

I'll give it a shot to regenerate the docs without the master.
